# Generated by Django 4.0.2 on 2022-03-01 13:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=12)),
                ('language', models.CharField(max_length=5)),
                ('currency', models.CharField(max_length=3)),
            ],
            options={
                'db_table': 'provider',
            },
        ),
    ]
